### ISSUE TITLE
Convert tag add process to use existing messages

### ISSUE THREAD

**Issue by Drowrin** [Drowrin/Weeabot#4]
Currently, it can be a pain to add tags on mobile. Instead, users often  simply post an image with "please tag". Then another user must then get the image, add the tag, and credit the original user. This wastes time, effort, and sends many messages and images to a channel.

Additionally, adding an item with multiple tags currently requires multiple calls. Once to add the item itself and a single tag, and once to add the additional tag(s).

Instead, the command should be altered to take all the necessary info from an existing message to add it as a tag. This will solve both problems above.

The new proposed tag add process:

1. User sends the message they want to add as a tag
2. User calls the `tag add` command immediately after, or later with a message id
3. Request is elevated as necessary

In this way, mobile users can call `tag add` after their message to add tags, and multiple tags can be added simultaneously by one call.

**Comment by Svered** [comment]
One issue I can see with this is how would people get the message ID to add tags later?

**Comment by Drowrin** [comment]
not possible on mobile, but tagging isn't possible at all on iOS at the moment. This would still be a positive change for iOS users by being able to call `tag add` after posting. Even if someone else posts before them, and they have to ask for someone else to tag, it makes the process easier for the one who tags it.

 On desktop with developer mode enabled in appearance you can `right click ->copy ID`. Can make note of that in the `help` for the command.

**Comment by Svered** [comment]
I could also think of a possible improvement to current tagging functionality that could possibly be implemented if current tagging functionality stays along with this system.

**Comment by Drowrin** [comment]
Can also add interactive tagging through reactions.

1. User reacts with a specific emoji chosen for tagging
2. Bot asks them for tags or if it should abort the process
3. Request elevated as needed.

**Comment by Drowrin** [comment]
Current functionality could stay under a different name.

**Comment by Drowrin** [comment]
Partially complete. Needs reaction based tagging. Also considering reorganizing all tag commands that add tags as subcommands of tag add.
